### ISSUE TITLE
[Endpoints] User data endpoints

### ISSUE THREAD

**Issue by LucaStefan112** [LucaStefan112/MedConnect-Server#12]
Create the user data endpoints. All the endpoints should work under ''/users" route. The most important endpoints should be:

1. Check user token validity
2. Get user data
3. Get user's appointments
4. Get user's analyses
5. Update user data

Future endpoints will be added

**Comment by omerdikyol** [comment]
How are we getting user token from register/login part? Do we receive token and verify it, or receive user's data and log him again?

**Comment by LucaStefan112** [comment]
When a user is registered he will be redirected to login. When a user logs in the auth app sends the request to the server. If the data is valid the server returns a JWT to the auth app, which redirects the user to M2 app at /auth-redirect/:JWT. Our app will take the JWT from the url params and it will validate with our server. The server will return a '{error: boolean, message: string}' json which will indicate if the token is valid or not. Also, our server will asign this token to the client such that the client can't see the token, but for each request sent, the server will be able to see it. Whenever the token has expired or is not valid the server will return to the client a custom response, and our client will redirect the user to the auth app.
