### ISSUE TITLE
[Endpoints] Scheduling appointment endpoints

### ISSUE THREAD

**Issue by LucaStefan112** [LucaStefan112/MedConnect-Server#13]
Create the endpoints for the appointment component. The component will need this main endpoints:

- Get hospital specialisations
- Get doctors for a certain specialization
- Get available scheduling intervals for a certain doctor in a certain time-frame
- Schedule appointment for a user, in a certain interval with a certain doctor

Future endpoints will be added

**Comment by omerdikyol** [comment]
@MariusAchitei you might need to add "specialization" attribute to the user to get doctors for a certaion specialization:
specialization: string;
and
specialization: {
        type: String,
        required: false,
        enum: <You can create array at ./src/helper/enum.ts, then import it and write it here>,
},
